CREATE TABLE `leadGenAgents` (
	`id` int AUTO_INCREMENT NOT NULL,
	`clientId` int NOT NULL,
	`userId` int NOT NULL,
	`name` varchar(255) NOT NULL,
	`industry` varchar(100),
	`location` varchar(255),
	`radius` int DEFAULT 25,
	`targetKeywords` json,
	`filters` json,
	`outreachChannel` enum('sms','email','both') DEFAULT 'both',
	`outreachTone` enum('professional','friendly','urgent','consultative') DEFAULT 'friendly',
	`valueProposition` text,
	`status` enum('draft','active','paused') NOT NULL DEFAULT 'draft',
	`lastRunAt` timestamp,
	`totalProspectsFound` int DEFAULT 0,
	`totalLeadsSaved` int DEFAULT 0,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `leadGenAgents_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `leadGenResults` (
	`id` int AUTO_INCREMENT NOT NULL,
	`agentId` int NOT NULL,
	`clientId` int NOT NULL,
	`businessName` varchar(255) NOT NULL,
	`address` text,
	`phone` varchar(30),
	`website` varchar(500),
	`googlePlaceId` varchar(255),
	`rating` decimal(3,1),
	`reviewCount` int,
	`isUnclaimed` boolean DEFAULT false,
	`hasWebsite` boolean DEFAULT true,
	`opportunityScore` int DEFAULT 0,
	`smsMessage` text,
	`emailSubject` varchar(255),
	`emailBody` text,
	`status` enum('new','outreach_sent','responded','saved_as_lead','dismissed') NOT NULL DEFAULT 'new',
	`savedLeadId` int,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `leadGenResults_id` PRIMARY KEY(`id`)
);
