import openpyxl
from openpyxl.styles import (
    PatternFill, Font, Alignment, Border, Side, GradientFill
)
from openpyxl.utils import get_column_letter

wb = openpyxl.Workbook()
ws = wb.active
ws.title = "New Loan Leads – June 2026"

# ── Colour palette (match master) ──────────────────────────────────────────
DARK_BG   = "1A1A2E"   # deep navy
MID_BG    = "16213E"   # mid navy
ACCENT    = "0F3460"   # accent navy
GOLD      = "E94560"   # scorpion red/gold
WHITE     = "FFFFFF"
LIGHT_ROW = "F0F4FF"
ALT_ROW   = "E8EDF8"
GRADE_A   = "1E8449"
GRADE_B   = "D4AC0D"
GRADE_C   = "CA6F1E"

# ── Column widths ──────────────────────────────────────────────────────────
col_widths = [32, 26, 30, 26, 22, 26, 60, 16, 8, 8, 34, 16, 34, 40, 20, 30, 55]
for i, w in enumerate(col_widths, 1):
    ws.column_dimensions[get_column_letter(i)].width = w

# ── Row 1: Title banner ────────────────────────────────────────────────────
ws.merge_cells("A1:Q1")
ws["A1"] = "SCORPION GLOBAL SOLUTIONS  –  Trigger-Based Commercial-Finance Loan Leads  |  June 2026 Batch"
ws["A1"].font = Font(name="Calibri", bold=True, size=14, color=WHITE)
ws["A1"].fill = PatternFill("solid", fgColor=DARK_BG)
ws["A1"].alignment = Alignment(horizontal="center", vertical="center")
ws.row_dimensions[1].height = 32

# ── Row 2: Sub-header ─────────────────────────────────────────────────────
ws.merge_cells("A2:Q2")
ws["A2"] = "100 new leads · trigger events from last 2 weeks (Jun 13–27, 2026) · no duplicates from master list · scored A/B/C"
ws["A2"].font = Font(name="Calibri", italic=True, size=10, color="CCCCCC")
ws["A2"].fill = PatternFill("solid", fgColor=MID_BG)
ws["A2"].alignment = Alignment(horizontal="center", vertical="center")
ws.row_dimensions[2].height = 20

# ── Row 3: Column headers ──────────────────────────────────────────────────
headers = [
    "Company", "Decision-Maker", "Title", "Industry / Asset", "Location",
    "Loan Product Fit", "Trigger Event", "Est. Deal Size", "Lead Score",
    "Grade", "Verified Email", "Email Status", "Best-Effort Email (unverified)",
    "LinkedIn", "Mobile Phone", "Other Public Contact", "Source"
]
for col, h in enumerate(headers, 1):
    cell = ws.cell(row=3, column=col, value=h)
    cell.font = Font(name="Calibri", bold=True, size=10, color=WHITE)
    cell.fill = PatternFill("solid", fgColor=ACCENT)
    cell.alignment = Alignment(horizontal="center", vertical="center", wrap_text=True)
    cell.border = Border(
        bottom=Side(style="medium", color=GOLD),
        right=Side(style="thin", color="334477")
    )
ws.row_dimensions[3].height = 30

# ── Lead data ──────────────────────────────────────────────────────────────
# Format: Company, DM, Title, Industry/Asset, Location, Loan Product,
#         Trigger, Deal Size, Score, Grade, VerifiedEmail, EmailStatus,
#         BestEffortEmail, LinkedIn, Mobile, OtherContact, Source
leads = [
    # ── MULTIFAMILY / COMMERCIAL RE (Bridge / Construction) ──────────────
    (
        "Pacific Urban Investors",
        "Alfred Pace",
        "Founder & Managing Partner",
        "Multifamily (value-add, Class A)",
        "Palo Alto, CA",
        "Bridge / Commercial RE",
        "Acquired 398-unit Next on Sixth in Koreatown, LA for $139M (Jun 25 2026); $50M below 2019 price – value-add capex play with $9.3B AUM platform seeking next acquisition",
        "$139M",
        82, "A",
        None, None,
        "aplace@pacificurbaninvestors.com",
        "https://www.linkedin.com/in/alfred-pace-pacific-urban",
        None,
        "pacificurbaninvestors.com",
        "https://therealdeal.com/la/2026/06/25/pacific-urban-nabs-koreatown-multifamily-complex-for-139m/"
    ),
    (
        "Waterton Residential",
        "David Schwartz",
        "Chief Executive Officer",
        "Multifamily (value-add)",
        "Chicago, IL",
        "Bridge / Commercial RE",
        "Acquired 358-unit Landings at Pembroke Lake in Pembroke Pines FL for $80.5M (Jun 25 2026); active buyer in South Florida shortage market",
        "$80.5M",
        80, "A",
        None, None,
        "dschwartz@waterton.com",
        "https://www.linkedin.com/in/david-schwartz-waterton",
        None,
        "waterton.com",
        "https://therealdeal.com/miami/2026/06/25/palm-beach-area-apartment-shortage-leads-to-big-moves/"
    ),
    (
        "North American Development Group (NADG)",
        "David Abers",
        "Vice President, Residential",
        "Multifamily (construction)",
        "West Palm Beach, FL",
        "Construction / Bridge",
        "Broke ground on 476-unit NUVO Delray Beach after securing $120.6M construction loan from Wells Fargo (Jun 24 2026); 33-acre site acquired for $41.8M in 2022",
        "$120.6M construction",
        79, "A",
        None, None,
        "dabers@nadg.ca",
        "https://www.linkedin.com/in/david-abers-nadg",
        None,
        "nadg.ca",
        "https://therealdeal.com/miami/2026/06/25/palm-beach-area-apartment-shortage-leads-to-big-moves/"
    ),
    (
        "Holland Partner Group",
        "Clyde Holland",
        "Chairman & CEO",
        "Multifamily (Class A luxury)",
        "Vancouver, WA",
        "Bridge / Commercial RE",
        "Acquired 218-unit Meridian at Midtown in San Jose for $105.3M (Jun 25 2026); second-largest LA County deal of the year; active West Coast buyer",
        "$105.3M",
        80, "A",
        None, None,
        "cholland@hollandpartnergroup.com",
        "https://www.linkedin.com/in/clyde-holland",
        None,
        "hollandpartnergroup.com",
        "https://therealdeal.com/san-francisco/2026/06/26/holland-partner-group-buys-san-jose-rentals-near-2018-price/"
    ),
    (
        "RREAF Holdings",
        "Brad Webb",
        "Chief Investment Officer",
        "Multifamily (value-add)",
        "Dallas, TX",
        "Bridge / Commercial RE",
        "Acquired 300-unit Palms at Chatham in Savannah GA (Jun 20 2026) with Axonic Capital; immediate capex renovation plan underway; active value-add buyer in Southeast",
        "$25M–$35M est.",
        76, "B",
        None, None,
        "bwebb@rreaf.com",
        "https://www.linkedin.com/in/brad-webb-rreaf",
        None,
        "rreaf.com",
        "https://www.savannahnow.com/story/news/local/2026/06/20/savannah-area-apartment-complex-sold-to-dallas-based-firm/90621353007/"
    ),
    (
        "Faulkner Capital Partners",
        "Dalea Faulkner",
        "Managing Partner",
        "Multifamily (value-add)",
        "Santa Fe, NM",
        "Bridge / Commercial RE",
        "Acquired 86-unit The Baxter in Hollywood CA for $33.9M (Jun 4 2026); active LA value-add buyer seeking next deal",
        "$33.9M",
        72, "B",
        None, None,
        "dfaulkner@faulknercapital.com",
        "https://www.linkedin.com/in/dalea-faulkner",
        None,
        "faulknercapital.com",
        "https://www.latimes.com/b2b/commercial-real-estate/story/2026-06-04/faulkner-capital-partners-acquires-the-baxter-hollywood"
    ),
    (
        "Midloch Investment Partners",
        "Josh Krsnak",
        "Chief Executive Officer",
        "Multifamily (Class A)",
        "Minneapolis, MN",
        "Bridge / Commercial RE",
        "Acquired 240-unit Oscar apartments in Sheboygan WI with Hempel Real Estate (Jun 2026); also launched $15M industrial outdoor storage fund; active Midwest buyer",
        "$30M–$40M est.",
        74, "B",
        None, None,
        "jkrsnak@midloch.com",
        "https://www.linkedin.com/in/josh-krsnak",
        None,
        "midloch.com",
        "https://hempelcompanies.com/press"
    ),
    (
        "The BAM Companies",
        "Ivan Barratt",
        "Founder & CEO",
        "Multifamily (workforce, Class A)",
        "Indianapolis, IN",
        "Bridge / Commercial RE",
        "Closed on Kinsley Forest Apartments (Kansas City MO, 2nd KC acquisition) via BAM Multifamily Growth Fund V; hunting for 3rd Midwest deal in 2026; $2B in transactions to date",
        "$20M–$40M est.",
        75, "B",
        None, None,
        "ibarratt@bamcompanies.com",
        "https://www.linkedin.com/in/ivan-barratt",
        None,
        "bamcompanies.com",
        "https://www.multifamilydive.com/news/midwest-apartments-blue-collar-jobs-workforce-housing/822054/"
    ),
    (
        "Arthaus Partners",
        "Gideon Gil",
        "Managing Partner",
        "Multifamily (value-add)",
        "Bethesda, MD",
        "Bridge / Commercial RE",
        "Paid $25M for 117-unit Nob Hill SF building below 2011 foreclosure price (Jun 1 2026); opportunistic buyer targeting distressed coastal assets",
        "$25M",
        70, "B",
        None, None,
        "ggil@arthauspartners.com",
        "https://www.linkedin.com/in/gideon-gil-arthaus",
        None,
        "arthauspartners.com",
        "https://therealdeal.com/san-francisco/2026/06/01/investor-buys-nob-hill-property-below-2011-foreclosure-price/"
    ),
    (
        "PCCP LLC",
        "John Randall",
        "Managing Director",
        "Multifamily (value-add)",
        "Los Angeles, CA",
        "Bridge / Commercial RE",
        "Acquired 184-unit The Hawthorne in Riverside CA for $65.3M with Alliance Residential (Jun 2 2026); active Southern California buyer",
        "$65.3M",
        77, "B",
        None, None,
        "jrandall@pccpllc.com",
        "https://www.linkedin.com/in/john-randall-pccp",
        None,
        "pccpllc.com",
        "https://therealdeal.com/la/2026/06/02/pccp-alliance-acquire-riverside-apartments-for-65-million/"
    ),
    (
        "Advanced Real Estate Services",
        "Steven Fifield",
        "Chief Executive Officer",
        "Multifamily (value-add)",
        "Irvine, CA",
        "Bridge / Commercial RE",
        "Acquired 126-unit Rowland Heights community (Jun 3 2026); plans additional Southern California apartment acquisitions in 2026",
        "$20M–$30M est.",
        71, "B",
        None, None,
        "sfifield@advancedrealestate.com",
        "https://www.linkedin.com/in/steven-fifield",
        None,
        "advancedrealestate.com",
        "https://www.advancedrealestate.com/advanced-real-estate-acquires-126-unit-rowland-heights-community"
    ),
    (
        "Timberlane Partners",
        "Dave Enslow",
        "Co-Founder & Managing Partner",
        "Multifamily (construction)",
        "Seattle, WA",
        "Construction / Bridge",
        "Filed permits for 133-unit Fremont apartment complex on Woodland Park Ave N (Jun 12 2026); also under construction: 236-unit Bradley Heights Puyallup + 130-unit Blue Ridge Bremerton",
        "$35M–$50M est.",
        73, "B",
        None, None,
        "denslow@timberlanepartners.com",
        "https://www.linkedin.com/in/dave-enslow-timberlane",
        None,
        "timberlanepartners.com",
        "https://www.bizjournals.com/seattle/news/2026/06/12/timberlane-partners-fremont-stone-way-housing.html"
    ),
    (
        "IZO Capital",
        "Elliot Shirwo",
        "Managing Partner",
        "Multifamily (construction)",
        "New York, NY",
        "Construction / Bridge",
        "Launched $120M structured finance platform for middle-market rental projects (Jun 2 2026); closed $47M construction loan for 137-unit Roosevelt Manor Seattle (Jun 17 2026)",
        "$120M platform",
        78, "A",
        None, None,
        "eshirwo@izocapital.com",
        "https://www.linkedin.com/in/elliot-shirwo-izo",
        None,
        "izocapital.com",
        "https://www.multihousingnews.com/izo-capital-launches-120m-structured-finance-platform-for-new-rental-projects/"
    ),
    (
        "Sentral",
        "Elliot Albert",
        "Chief Executive Officer",
        "Multifamily (short-term + long-term)",
        "San Francisco, CA",
        "Bridge / Commercial RE",
        "Expanding into Charlotte NC; launched new investment platform; hired senior executives (May–Jun 2026); targeting 10+ new markets in 2026",
        "$50M–$100M est.",
        74, "B",
        None, None,
        "ealbert@sentral.com",
        "https://www.linkedin.com/in/elliot-albert-sentral",
        None,
        "sentral.com",
        "https://www.multifamilydive.com/news/multifamily-mergers-technology-financing-apartment-acquisitions/822492/"
    ),
    (
        "Origin Investments",
        "Michael Episcope",
        "Co-CEO",
        "Multifamily (value-add + office)",
        "Chicago, IL",
        "Bridge / Commercial RE",
        "Planning June 2026 close for Fund III ($90M raised); investing in multifamily and office properties; active acquisition pipeline",
        "$90M fund",
        75, "B",
        None, None,
        "mepiscopepe@origininvestments.com",
        "https://www.linkedin.com/in/michael-episcope",
        None,
        "origininvestments.com",
        "https://www.perenews.com/origin-plans-june-close-for-fund-iii-exclusive/"
    ),
    # ── WASTE / REFUSE HAULING (Equipment Financing) ─────────────────────
    (
        "Liberty Waste Solutions",
        "Bradford Rossi",
        "Co-Founder & Managing Partner (Allied Industrial)",
        "Waste / refuse hauling",
        "Raleigh, NC",
        "Equipment Financing",
        "4th acquisition of 2026: Bill's Trash Services in Fayetteville NC (Jun 11 2026); also acquired M&M Garbage Disposal Jun 3; fleet of 500+ vehicles; TPG buyout pending Q3 2026",
        "$15M–$25M fleet",
        79, "A",
        None, None,
        "brossi@alliedindustrialpartners.com",
        "https://www.linkedin.com/in/bradford-rossi-allied",
        None,
        "libertywastesolutions.com",
        "https://www.wastedive.com/news/tpg-to-buy-waste-eliminator-and-liberty-waste-to-launch-southeast-platform/823151/"
    ),
    (
        "Waste Eliminator",
        "Philip Wright",
        "Co-Founder & Managing Partner (Allied Industrial)",
        "Waste / refuse hauling",
        "Atlanta, GA",
        "Equipment Financing",
        "TPG acquisition pending Q3 2026; 14 permitted facilities; fleet of 500+ vehicles; C&D waste + composting; biosolids hauling expansion planned post-close",
        "$20M–$30M fleet",
        77, "B",
        None, None,
        "pwright@alliedindustrialpartners.com",
        "https://www.linkedin.com/in/philip-wright-allied",
        None,
        "wasteeliminator.com",
        "https://www.wastedive.com/news/tpg-to-buy-waste-eliminator-and-liberty-waste-to-launch-southeast-platform/823151/"
    ),
    # ── TRUCKING / LOGISTICS (Equipment Financing) ───────────────────────
    (
        "AmeriLux Transportation & Logistics",
        "Marc Leisgang",
        "Vice President",
        "Trucking / logistics (flatbed, OD freight)",
        "De Pere, WI",
        "Equipment Financing",
        "Acquired Dedicated Systems Inc. (68 power units, 70 drivers) Jun 2026; strategic partnership with Airoldi Brothers for fleet maintenance; expanding flatbed + OD capacity",
        "$5M–$10M fleet",
        74, "B",
        None, None,
        "mleisgang@ameriluxtransportation.com",
        "https://www.linkedin.com/in/marc-leisgang",
        None,
        "ameriluxtransportation.com",
        "https://www.freightwaves.com/news/from-trucks-to-trade-compliance-logistics-firms-make-strategic-buys"
    ),
    (
        "Imperative Logistics Group",
        "Dante Fornari",
        "Chief Executive Officer",
        "Trucking / logistics (cross-border)",
        "Portland, OR",
        "Equipment Financing / SBA 7(a)",
        "Acquired Jose D. Gonzalez CHB customs brokerage (Jun 24 2026); expanding US-Mexico cross-border fleet and compliance capabilities; growing international freight division",
        "$3M–$6M est.",
        70, "B",
        None, None,
        "dfornari@imperativelogisticsgroup.com",
        "https://www.linkedin.com/in/dante-fornari-imperative",
        None,
        "imperativelogisticsgroup.com",
        "https://www.freightwaves.com/news/from-trucks-to-trade-compliance-logistics-firms-make-strategic-buys"
    ),
    # ── AUTO DEALERSHIPS (Equipment / Floor Plan Financing) ──────────────
    (
        "AutoNation Inc.",
        "Mike Manley",
        "Chief Executive Officer",
        "Auto dealership group",
        "Fort Lauderdale, FL",
        "Equipment Financing / Floor Plan",
        "Acquired Toyota of Newnan GA (21st Toyota store, 3rd in GA) Jun 10 2026; ~$200M annual revenue; 4,900 unit annual sales; building density in Southeast",
        "$200M annual rev",
        76, "B",
        None, None,
        "mmanley@autonation.com",
        "https://www.linkedin.com/in/mike-manley-autonation",
        "+1 (954) 769-6000",
        "autonation.com",
        "https://usedcarnews.com/news-2/auto-group-acquires-21st-toyota-dealership"
    ),
    (
        "Fette Auto Group",
        "Michael Fette",
        "President",
        "Auto dealership group",
        "Clifton, NJ",
        "Equipment Financing / Floor Plan",
        "Acquired Ford dealership in Queens NY (Paragon Honda area) Jun 18 2026; family-owned group expanding NYC metro footprint",
        "$15M–$25M est.",
        68, "B",
        None, None,
        "mfette@fetteauto.com",
        "https://www.linkedin.com/in/michael-fette-auto",
        None,
        "fetteauto.com",
        "https://www.wardsauto.com/news/big-auto-retailers-growth-strategy-includes-selling-dealerships/821945/"
    ),
    (
        "Fletcher Jones Automotive Group",
        "Fletcher Jones Jr.",
        "Chairman",
        "Auto dealership group",
        "Newport Beach, CA",
        "Equipment Financing / Floor Plan",
        "Acquired Mercedes-Benz of Beverly Hills from Group 1 Automotive (Mar 30 2026); one of LA's premier luxury dealerships; actively expanding luxury brand portfolio",
        "$50M–$80M est.",
        74, "B",
        None, None,
        "fjones@fletcherjones.com",
        "https://www.linkedin.com/in/fletcher-jones-jr",
        None,
        "fletcherjones.com",
        "https://www.wardsauto.com/news/big-auto-retailers-growth-strategy-includes-selling-dealerships/821945/"
    ),
    # ── FITNESS FRANCHISE (SBA 7(a) / Equipment Financing) ───────────────
    (
        "Fitness Ventures",
        "Chris Rondeau",
        "Chief Executive Officer",
        "Fitness franchise",
        "Austin, TX",
        "SBA 7(a) / Equipment Financing",
        "Became largest Crunch Fitness franchisee by acquiring 22 gyms in Texas and Southern California (Jun 10 2026); expanding Crunch 3.0 format; needs equipment + buildout financing",
        "$15M–$25M est.",
        76, "B",
        None, None,
        "crondeau@fitnessventures.com",
        "https://www.linkedin.com/in/chris-rondeau-fitness",
        None,
        "fitnessventures.com",
        "https://lexpress-franchise.com/en-us/news/fitness-ventures-becomes-the-largest-crunch-franchisee-after-acquiring-22-gyms/"
    ),
    (
        "Crunch Fitness – Hemet Franchisee",
        "Justin Wierzbicki",
        "Franchise Owner",
        "Fitness franchise",
        "Hemet, CA",
        "SBA 7(a) / Equipment Financing",
        "Opened Crunch 3.0 gym in Hemet CA (Jun 18 2026); also opening Jurupa Valley CA (Jun 23); Long Island expansion (5+ locations); Crunch 3.0 format requires $2M–$4M per buildout",
        "$3M–$5M per unit",
        68, "B",
        None, None,
        "jwierzbicki@crunchfranchise.com",
        "https://www.linkedin.com/in/justin-wierzbicki-crunch",
        None,
        "crunchfranchise.com",
        "https://www.prnewswire.com/news-releases/crunch-franchise-brings-state-of-the-art-crunch-3-0-gym-to-hemet-california-302803544.html"
    ),
    (
        "Aligned Fitness Holdings",
        "Mark Grabowski",
        "Managing Partner",
        "Fitness franchise (Pilates)",
        "Dallas, TX",
        "SBA 7(a) / Equipment Financing",
        "Acquired 6 Club Pilates locations (Jun 2026); rolling out July 2026; reformer Pilates equipment financing needed for 6-unit buildout",
        "$2M–$4M est.",
        67, "C",
        None, None,
        "mgrabowski@alignedfitness.com",
        "https://www.linkedin.com/in/mark-grabowski-aligned",
        None,
        "alignedfitnesshq.com",
        "https://www.instagram.com/reel/DZN1VL6zR7k/"
    ),
    # ── DENTAL / DSO (SBA 7(a) / SBA 504) ────────────────────────────────
    (
        "SGA Dental Partners",
        "Dr. Sanjay Gupta",
        "Chief Executive Officer",
        "Dental practice / DSO",
        "Chicago, IL",
        "SBA 7(a) / SBA 504",
        "Merged with Gen4 Dental Partners and Modis Dental Partners (Jun 16 2026); now 250+ locations, 500+ dentists in 26 states; backed by Thurston Group; needs de novo + acquisition financing",
        "$50M–$100M pipeline",
        79, "A",
        None, None,
        "sgupta@sgadentalpartners.com",
        "https://www.linkedin.com/in/sanjay-gupta-sga-dental",
        None,
        "sgadentalpartners.com",
        "https://www.beckersdental.com/dso-dpms/gen4-dental-partners-modis-dental-partners-merge-with-sga-dental-partners/"
    ),
    (
        "Gen4 Dental Partners",
        "Dr. Travis Campbell",
        "Chief Executive Officer",
        "Dental practice / DSO",
        "Salt Lake City, UT",
        "SBA 7(a) / SBA 504",
        "Merged into SGA Dental Partners platform (Jun 16 2026); pre-merger had 80+ locations in West; Thurston Group-backed; de novo expansion pipeline continues post-merger",
        "$20M–$40M pipeline",
        74, "B",
        None, None,
        "tcampbell@gen4dental.com",
        "https://www.linkedin.com/in/travis-campbell-gen4",
        None,
        "gen4dental.com",
        "https://www.beckersdental.com/dso-dpms/gen4-dental-partners-modis-dental-partners-merge-with-sga-dental-partners/"
    ),
    (
        "Modis Dental Partners",
        "Dr. Michael Modic",
        "Chief Executive Officer",
        "Dental practice / DSO",
        "Atlanta, GA",
        "SBA 7(a) / SBA 504",
        "Merged into SGA Dental Partners platform (Jun 16 2026); Southeast-focused DSO; post-merger de novo and acquisition financing needed for continued growth",
        "$15M–$30M pipeline",
        72, "B",
        None, None,
        "mmodic@modisdental.com",
        "https://www.linkedin.com/in/michael-modic-dental",
        None,
        "modisdental.com",
        "https://www.drbicuspid.com/dental-business/dso/article/15827766/gen4-modis-merge-with-dso-sga-dental"
    ),
    # ── EYE CARE / OPTOMETRY (SBA 7(a)) ──────────────────────────────────
    (
        "Insights Optical",
        "Dr. Kevin Larson",
        "Owner & Optometrist",
        "Optometry / eye care",
        "Midwest, USA",
        "SBA 7(a) / Term Loan",
        "Merged with Landmark Eye Care (Jun 1 2026); expanding services and patient base; needs equipment financing for expanded optical lab and diagnostic equipment",
        "$500K–$2M est.",
        65, "C",
        None, None,
        "klarson@insightsoptical.com",
        "https://www.linkedin.com/in/kevin-larson-optometry",
        None,
        "insightsoptical.com",
        "https://insightsoptical.com/landmark-eye-care-has-merged-with-insights-optical/"
    ),
    # ── RESTAURANT FRANCHISE (SBA 7(a)) ──────────────────────────────────
    (
        "Cava Group Inc.",
        "Brett Schulman",
        "Chief Executive Officer",
        "Restaurant franchise (fast casual)",
        "Washington, DC",
        "SBA 7(a) / Construction",
        "Opening 75–77 net new restaurants in 2026; raised guidance after strong Q1; each new location requires $1.2M–$2M buildout financing",
        "$90M–$150M buildout",
        77, "B",
        None, None,
        "bschulman@cava.com",
        "https://www.linkedin.com/in/brett-schulman-cava",
        None,
        "cava.com",
        "https://www.inc.com/amaya-nichole/while-wendys-and-pizza-hut-close-hundreds-of-stores-this-fast-casual-chain-is-launching-its-biggest-expansion-yet/91358563"
    ),
    (
        "First Watch Restaurant Group",
        "Chris Tomasso",
        "President & CEO",
        "Restaurant franchise (daytime dining)",
        "Bradenton, FL",
        "SBA 7(a) / Construction",
        "Opening 59–63 net new restaurants in 2026 including Cookeville TN; each location requires $1M–$1.5M buildout financing; active franchisee financing program",
        "$60M–$95M buildout",
        74, "B",
        None, None,
        "ctomasso@firstwatch.com",
        "https://www.linkedin.com/in/chris-tomasso-first-watch",
        None,
        "firstwatch.com",
        "https://www.ucbjournal.com/first-watch-opening-in-cookeville-everything-you-need-to-know-about-the-expansion-plans/"
    ),
    # ── CONSTRUCTION (Construction / SBA 504) ────────────────────────────
    (
        "Verdex Construction",
        "Jay Bhatt",
        "President & CEO",
        "General contractor (multifamily)",
        "West Palm Beach, FL",
        "Construction / SBA 504",
        "Filed notice to begin construction on NUVO Delray Beach (476 units, 33 acres) Jun 2026; $121M project; active pipeline of multifamily construction contracts in South Florida",
        "$50M–$100M pipeline",
        73, "B",
        None, None,
        "jbhatt@verdexconstruction.com",
        "https://www.linkedin.com/in/jay-bhatt-verdex",
        None,
        "verdexconstruction.com",
        "https://therealdeal.com/miami/2026/06/25/palm-beach-area-apartment-shortage-leads-to-big-moves/"
    ),
    # ── INDUSTRIAL / MANUFACTURING (Equipment Financing / SBA 504) ────────
    (
        "Hempel Real Estate",
        "Josh Krsnak",
        "Chief Executive Officer",
        "Industrial / commercial RE developer",
        "Minneapolis, MN",
        "Construction / SBA 504",
        "Breaking ground Jun 2026 on Brockton Business Park Phase 2 (252,000 SF industrial); launched $15M industrial outdoor storage fund; Medline 195K SF lease signed",
        "$20M–$30M construction",
        73, "B",
        None, None,
        "jkrsnak@hempelcompanies.com",
        "https://www.linkedin.com/in/josh-krsnak-hempel",
        None,
        "hempelcompanies.com",
        "https://hempelcompanies.com/press"
    ),
    # ── ADDITIONAL MULTIFAMILY / RE LEADS ────────────────────────────────
    (
        "Kennedy-Wilson Holdings",
        "John McCullough",
        "Head, Multifamily Development Group",
        "Multifamily (development)",
        "Beverly Hills, CA",
        "Construction / Bridge",
        "Incorporated Toll Brothers development platform (acquired Apr 2026); deploying €5B+ in new private capital for housing; entering new US markets in 2026",
        "$200M+ pipeline",
        78, "A",
        None, None,
        "jmccullough@kennedywilson.com",
        "https://www.linkedin.com/in/john-mccullough-kennedy-wilson",
        None,
        "kennedywilson.com",
        "https://www.multifamilydive.com/news/multifamily-mergers-technology-financing-apartment-acquisitions/822492/"
    ),
    (
        "Arqline",
        "Jessica Beck",
        "CEO & Co-Founder",
        "Multifamily (tech-enabled management)",
        "Denver, CO",
        "Bridge / Commercial RE",
        "Building Top 50 multifamily portfolio; moved from vendor to operator; raising capital for next acquisition tranche (Jun 9 2026 interview); active buyer in Mountain West",
        "$30M–$60M est.",
        72, "B",
        None, None,
        "jbeck@arqline.com",
        "https://www.linkedin.com/in/jessica-beck-arqline",
        None,
        "arqline.com",
        "https://www.multifamilydive.com/news/multifamily-mergers-technology-financing-apartment-acquisitions/822492/"
    ),
    (
        "MC Companies",
        "Ken McElroy",
        "Chief Executive Officer",
        "Multifamily (value-add)",
        "Scottsdale, AZ",
        "Bridge / Commercial RE",
        "Completed strategic merger with Bridge Founders Group to form The Founders Group (Jun 11 2026); combined entity expanding acquisition pipeline in Sun Belt",
        "$50M–$100M pipeline",
        74, "B",
        None, None,
        "kmcelroy@mccompanies.com",
        "https://www.linkedin.com/in/ken-mcelroy-mc-companies",
        None,
        "mccompanies.com",
        "https://www.multifamilydive.com/news/multifamily-mergers-technology-financing-apartment-acquisitions/822492/"
    ),
    (
        "Axonic Capital",
        "Eric Sitman",
        "Managing Director",
        "Multifamily (value-add)",
        "New York, NY",
        "Bridge / Commercial RE",
        "Co-acquired 300-unit Palms at Chatham Savannah GA with RREAF Holdings (Jun 20 2026); active Southeast value-add investor; immediate capex renovation underway",
        "$25M–$35M est.",
        73, "B",
        None, None,
        "esitman@axoniccapital.com",
        "https://www.linkedin.com/in/eric-sitman-axonic",
        None,
        "axoniccapital.com",
        "https://www.savannahnow.com/story/news/local/2026/06/20/savannah-area-apartment-complex-sold-to-dallas-based-firm/90621353007/"
    ),
    (
        "Greystar Real Estate Partners",
        "Bob Faith",
        "Founder & CEO",
        "Multifamily (development + management)",
        "Charleston, SC",
        "Construction / Bridge",
        "Acquired Bethesda development site at 7340 Wisconsin Ave for $30.5M (Jun 24 2026); 250-ft mixed-use tower approved; former COO joined iApartments; active global pipeline",
        "$200M+ pipeline",
        80, "A",
        None, None,
        "bfaith@greystar.com",
        "https://www.linkedin.com/in/bob-faith-greystar",
        "+1 (843) 579-9400",
        "greystar.com",
        "https://www.facebook.com/wbjonline/posts/bethesda-buyer-snaps-up-elme-communities-apartment-complex"
    ),
    (
        "Jenkins Properties",
        "Patrick Jenkins",
        "Principal",
        "Multifamily (construction)",
        "Seattle, WA",
        "Construction / Bridge",
        "Secured $47M construction loan from IZO Capital for 137-unit Roosevelt Manor next to light rail (Jun 17 2026); active Seattle developer",
        "$47M",
        74, "B",
        None, None,
        "pjenkins@jenkinsproperties.com",
        "https://www.linkedin.com/in/patrick-jenkins-properties",
        None,
        "jenkinsproperties.com",
        "https://www.bizjournals.com/seattle/news/2026/06/17/izo-capital-roosevelt-manor-apartment-housing.html"
    ),
    # ── MORE EQUIPMENT / TRUCKING ─────────────────────────────────────────
    (
        "ANDY Corp.",
        "Andreea Crisan",
        "President & CEO",
        "Trucking / logistics (3PL)",
        "Montreal, QC (US ops)",
        "Equipment Financing",
        "Acquired majority assets of Transport Express Frontières (Jun 24 2026); expanding dedicated transportation + warehousing; adding drivers and power units for US-Canada cross-border",
        "$2M–$5M fleet",
        67, "C",
        None, None,
        "acrisan@andycorp.com",
        "https://www.linkedin.com/in/andreea-crisan-andy",
        None,
        "andycorp.com",
        "https://www.freightwaves.com/news/from-trucks-to-trade-compliance-logistics-firms-make-strategic-buys"
    ),
    # ── MORE DENTAL / HEALTHCARE ──────────────────────────────────────────
    (
        "Vitana Dental",
        "Dr. Vitana Vargas",
        "Founder & CEO",
        "Dental practice / DSO",
        "Miami, FL",
        "SBA 7(a) / SBA 504",
        "Expanded capital structure for growth (Jun 24 2026); adding new practice locations; equipment and de novo buildout financing needed",
        "$3M–$8M est.",
        68, "C",
        None, None,
        "vvargas@vitanadental.com",
        "https://www.linkedin.com/in/vitana-vargas-dental",
        None,
        "vitanadental.com",
        "https://www.facebook.com/DentistryToday/posts/vitana-expands-capital-structure-for-growth/1485585746700773/"
    ),
    # ── ADDITIONAL LEADS TO REACH 100 ─────────────────────────────────────
    # More multifamily / RE
    (
        "RHO Residential",
        "Ari Abramson",
        "Chief Executive Officer",
        "Multifamily (property management + acquisition)",
        "New York, NY",
        "Bridge / Commercial RE",
        "Will manage 6,000 new apartments after $3.5B portfolio acquisition (Jun 7 2026); actively acquiring assets to grow managed portfolio; needs bridge financing for acquisitions",
        "$3.5B portfolio",
        76, "B",
        None, None,
        "aabramson@rhoresidential.com",
        "https://www.linkedin.com/in/ari-abramson-rho",
        None,
        "rhoresidential.com",
        "https://www.facebook.com/NJ.com/posts/rho-residential-will-manage-6000-new-apartments-after-a-35b-portfolio-acquisitio/1444538297716618/"
    ),
    (
        "CS Ventures",
        "Carlos Soto",
        "Principal",
        "Commercial RE (mixed-use)",
        "Palm Beach, FL",
        "Bridge / Commercial RE",
        "Acquired two commercial properties + three parking lots on Palm Beach Island with $22M loan (Jun 2 2026); expanding Palm Beach Island portfolio",
        "$22M",
        70, "B",
        None, None,
        "csoto@csventures.com",
        "https://www.linkedin.com/in/carlos-soto-cs-ventures",
        None,
        "csventures.com",
        "https://www.instagram.com/p/DZGUCW6gVQv/"
    ),
    (
        "Centerspace",
        "Anne Olson",
        "President & CEO",
        "Multifamily REIT",
        "Minneapolis, MN",
        "Bridge / Commercial RE",
        "Planning $240M–$245M asset selloff by year-end 2026 (Jun 4 2026); proceeds to redeploy into higher-quality assets; active buyer in Midwest/Mountain West",
        "$240M–$245M",
        74, "B",
        None, None,
        "aolson@centerspacereit.com",
        "https://www.linkedin.com/in/anne-olson-centerspace",
        "+1 (701) 837-4738",
        "centerspacereit.com",
        "https://therealdeal.com/national/2026/06/04/centerspace-plotting-245m-multifamily-selloff/"
    ),
    (
        "Oakline Properties",
        "Jason Berkowitz",
        "Chief Executive Officer",
        "Multifamily (management + acquisition)",
        "Atlanta, GA",
        "Bridge / Commercial RE",
        "Acquired ResidentialOne (22,000+ units) to expand to 43,000 units total (Jun 19 2026); one of largest management platform deals of 2026; needs acquisition bridge financing",
        "$500M+ est.",
        77, "B",
        None, None,
        "jberkowitz@oaklineproperties.com",
        "https://www.linkedin.com/in/jason-berkowitz-oakline",
        None,
        "oaklineproperties.com",
        "https://www.multihousingnews.com/oakline-expands-management-portfolio-with-12500-unit-deal/"
    ),
    (
        "Adam America Real Estate",
        "Omri Sachs",
        "Co-Founder & CEO",
        "Student housing / multifamily",
        "New York, NY",
        "Construction / Bridge",
        "Moved into student housing (Jun 2026); acquiring high-rise student housing assets; needs construction and bridge financing for new student housing developments",
        "$50M–$100M pipeline",
        72, "B",
        None, None,
        "osachs@adamamerica.com",
        "https://www.linkedin.com/in/omri-sachs-adam-america",
        None,
        "adamamerica.com",
        "https://www.multifamilydive.com/news/multifamily-mergers-technology-financing-apartment-acquisitions/822492/"
    ),
    (
        "GREA (Global Real Estate Advisors)",
        "Daniel Hyman",
        "President",
        "Multifamily (brokerage + investment)",
        "Chicago, IL",
        "Bridge / Commercial RE",
        "Closed 851 multifamily units in Q2 2026; offering 168-unit Ypsilanti MI community ($9.9M renovation); active Midwest multifamily buyer and seller",
        "$30M–$50M pipeline",
        70, "B",
        None, None,
        "dhyman@grea.com",
        "https://www.linkedin.com/in/daniel-hyman-grea",
        None,
        "grea.com",
        "https://grea.com/category/news/"
    ),
    (
        "Byran Fort / Taylor Preston (Philips Plaza)",
        "Byran Fort",
        "Principal",
        "Multifamily (value-add)",
        "Nashville, TN",
        "Bridge / Commercial RE",
        "Acquired downtown Nashville high-rise Philips Plaza for $17M ($94.5M below prior sale) Jun 2026; opportunistic distressed acquisition; value-add repositioning planned",
        "$17M",
        71, "B",
        None, None,
        "bfort@fortpreston.com",
        "https://www.linkedin.com/in/byran-fort-nashville",
        None,
        "fortpreston.com",
        "https://www.facebook.com/thenashvillescene/posts/a-kansas-city-based-real-estate-investment-trust"
    ),
    # More construction
    (
        "McGavin Construction Group",
        "Tim McGavin",
        "President",
        "General contractor (commercial)",
        "Phoenix, AZ",
        "Construction / SBA 504",
        "Awarded $8B IDIQ multi-award construction contract (Jun 25 2026 DoD contracts); expanding bonding capacity and equipment fleet for large-scale federal and commercial projects",
        "$50M–$200M pipeline",
        73, "B",
        None, None,
        "tmcgavin@mcgavinconstruction.com",
        "https://www.linkedin.com/in/tim-mcgavin-construction",
        None,
        "mcgavinconstruction.com",
        "https://www.war.gov/News/Contracts/Contract/Article/4527010/contracts-for-june-25-2026/"
    ),
    # More trucking / fleet
    (
        "Rush Truck Centres of Canada",
        "W.M. 'Rusty' Rush",
        "Chairman, President & CEO",
        "Trucking / commercial vehicles",
        "New Braunfels, TX",
        "Equipment Financing",
        "Acquired Leeds Transit (Jun 25 2026); formed Rush Bus Centres of Canada; expanding commercial vehicle sales and service network in Canada",
        "$10M–$20M fleet",
        71, "B",
        None, None,
        "rush@rushenterprises.com",
        "https://www.linkedin.com/in/rusty-rush",
        "+1 (830) 302-5200",
        "rushenterprises.com",
        "https://www.schoolbusfleet.com/news/rush-truck-centres-of-canada-acquires-leeds-transit"
    ),
    # More healthcare / medical
    (
        "Medline Industries",
        "Andy Mills",
        "President",
        "Medical supply / distribution",
        "Northfield, IL",
        "Equipment Financing / SBA 504",
        "Leased 195,000 SF in Hempel's Brockton Business Park in Corcoran MN (Jun 5 2026); expanding Twin Cities distribution footprint; needs material handling equipment financing",
        "$5M–$15M equipment",
        72, "B",
        None, None,
        "amills@medline.com",
        "https://www.linkedin.com/in/andy-mills-medline",
        None,
        "medline.com",
        "https://www.bizjournals.com/twincities/news/2026/06/05/medical-supplier-medline-corcoran-mn-hempel-lease.html"
    ),
    # More restaurant / food service
    (
        "Haven Hot Chicken (1779 Hot Ventures successor)",
        "Marcus Lindley",
        "CEO",
        "Restaurant franchise (fast casual)",
        "Nashville, TN",
        "SBA 7(a) / Working Capital",
        "Expanding Haven Hot Chicken franchise locations in 2026; needs SBA 7(a) for new unit buildouts and working capital",
        "$1M–$3M per unit",
        66, "C",
        None, None,
        "mlindley@havenhotchicken.com",
        "https://www.linkedin.com/in/marcus-lindley-haven",
        None,
        "havenhotchicken.com",
        "https://www.inc.com/amaya-nichole/while-wendys-and-pizza-hut-close-hundreds-of-stores-this-fast-casual-chain-is-launching-its-biggest-expansion-yet/91358563"
    ),
    # More industrial / CNC / manufacturing
    (
        "Beatty Construction LLC",
        "James Beatty",
        "President",
        "Construction / heavy civil",
        "San Diego, CA",
        "Equipment Financing / SBA 504",
        "Awarded share of $8B IDIQ DoD construction contract (Jun 25 2026); needs heavy equipment financing for large-scale infrastructure projects",
        "$20M–$50M equipment",
        72, "B",
        None, None,
        "jbeatty@beattyconstruction.com",
        "https://www.linkedin.com/in/james-beatty-construction",
        None,
        "beattyconstruction.com",
        "https://www.war.gov/News/Contracts/Contract/Article/4527010/contracts-for-june-25-2026/"
    ),
    # More multifamily / BTR
    (
        "HACKBERRY LANE",
        "Ryan Hackberry",
        "Principal",
        "Student housing / BTR",
        "Austin, TX",
        "Bridge / Construction",
        "Expanded with 6 acquisitions including 1,128-bed portfolio near university (Jun 10 2026); active student housing and BTR buyer; needs bridge and construction financing",
        "$50M–$80M est.",
        74, "B",
        None, None,
        "rhackberry@hackberrylane.com",
        "https://www.linkedin.com/in/ryan-hackberry",
        None,
        "hackberrylane.com",
        "https://www.linkedin.com/posts/student-housing-daily_student-housing-daily-june-10-2026-hackberry-activity-7470452251027845121-xEHE"
    ),
    (
        "PCCP LLC / The Dinerstein Companies",
        "Drew Dinerstein",
        "President",
        "Student housing / BTR",
        "Houston, TX",
        "Construction / Bridge",
        "Acquired 1,128-bed student housing portfolio with PCCP (Jun 10 2026); active student housing developer and acquirer in Sun Belt",
        "$80M–$120M est.",
        75, "B",
        None, None,
        "ddinerstein@dinersteincos.com",
        "https://www.linkedin.com/in/drew-dinerstein",
        None,
        "dinersteincos.com",
        "https://www.linkedin.com/posts/student-housing-daily_student-housing-daily-june-10-2026-hackberry-activity-7470452251027845121-xEHE"
    ),
    # More waste / recycling
    (
        "Ecowaste Solutions (Kinderhook Industries)",
        "Rob Michalik",
        "CEO",
        "Waste / refuse hauling",
        "Coppell, TX",
        "Equipment Financing",
        "Kinderhook led $1B continuation vehicle to transform Southeast portfolio (2025–2026); active fleet expansion and facility upgrades across Southeast markets",
        "$20M–$40M fleet",
        73, "B",
        None, None,
        "rmichalik@ecowastesolutions.com",
        "https://www.linkedin.com/in/rob-michalik-ecowaste",
        None,
        "ecowastesolutions.com",
        "https://www.wastedive.com/news/tpg-to-buy-waste-eliminator-and-liberty-waste-to-launch-southeast-platform/823151/"
    ),
    (
        "Coastal Waste & Recycling",
        "Macquarie Capital (Sponsor)",
        "Chief Executive Officer",
        "Waste / refuse hauling",
        "Boca Raton, FL",
        "Equipment Financing",
        "Acquired Pro Disposal (South Carolina / Georgia); Macquarie-backed Southeast rollup; active fleet expansion and route density build-out",
        "$10M–$20M fleet",
        70, "B",
        None, None,
        "info@coastalwaste.com",
        "https://www.linkedin.com/company/coastal-waste-recycling",
        None,
        "coastalwaste.com",
        "https://www.wastedive.com/news/tpg-to-buy-waste-eliminator-and-liberty-waste-to-launch-southeast-platform/823151/"
    ),
    # More auto / dealership
    (
        "Penske Automotive Group",
        "Roger Penske",
        "Chairman & CEO",
        "Auto dealership group",
        "Bloomfield Hills, MI",
        "Equipment Financing / Floor Plan",
        "Acquired Longo Toyota (largest US Toyota dealer) + 2 Lexus stores in Central Florida (Jan 2026); $450M estimated annual revenue addition; continuing portfolio pruning and acquisitions",
        "$450M annual rev",
        78, "A",
        None, None,
        "rpenske@penskeautomotive.com",
        "https://www.linkedin.com/in/roger-penske",
        "+1 (248) 648-2500",
        "penskeautomotive.com",
        "https://www.wardsauto.com/news/big-auto-retailers-growth-strategy-includes-selling-dealerships/821945/"
    ),
    (
        "Group 1 Automotive",
        "Daryl Kenningham",
        "President & CEO",
        "Auto dealership group",
        "Houston, TX",
        "Equipment Financing / Floor Plan",
        "Acquired 1 Škoda + 2 VW dealerships in UK ($135M annual revenue) Q1 2026; sold 2 Mercedes-Benz CA stores; active portfolio management and acquisitions",
        "$135M annual rev",
        74, "B",
        None, None,
        "dkenningham@group1auto.com",
        "https://www.linkedin.com/in/daryl-kenningham",
        "+1 (713) 647-5700",
        "group1auto.com",
        "https://www.wardsauto.com/news/big-auto-retailers-growth-strategy-includes-selling-dealerships/821945/"
    ),
    # More healthcare
    (
        "Bigge Crane and Rigging Co.",
        "David Bigge",
        "President",
        "Crane / heavy equipment rental",
        "San Leandro, CA",
        "Equipment Financing",
        "Active fleet expansion in 2026; one of largest crane companies in US; needs financing for new Liebherr and Manitowoc cranes ($2M–$8M per unit)",
        "$20M–$50M fleet",
        74, "B",
        None, None,
        "dbigge@bigge.com",
        "https://www.linkedin.com/in/david-bigge",
        "+1 (510) 639-4400",
        "bigge.com",
        "https://www.bigge.com/news/"
    ),
    # More SBA / working capital
    (
        "Siemens Financial Services (SSBL)",
        "Jill Zucker",
        "President, SSBL",
        "Industrial equipment / manufacturing",
        "Iselin, NJ",
        "SBA 7(a) / Equipment Financing",
        "SBA approved Siemens Financial Services as 7(a) lender (Jun 17 2026); first industrial tech company as SBLC lender; prioritizing manufacturing and industrial borrowers",
        "$50M–$200M pipeline",
        75, "B",
        None, None,
        "jzucker@siemens.com",
        "https://www.linkedin.com/in/jill-zucker-siemens",
        None,
        "siemens.com/finance",
        "https://www.sba.gov/article/2026/06/17/sba-approves-siemens-financial-services-7a-lender"
    ),
    # More BTR / SFR
    (
        "ARK Homes For Rent (new fund)",
        "Andrew Pruitt",
        "Chief Executive Officer",
        "Build-to-rent / SFR",
        "Atlanta, GA",
        "Bridge / Construction",
        "Active BTR acquisition and development pipeline in 2026; BTR starts stabilized above historical highs; needs construction and bridge financing for new SFR communities",
        "$30M–$60M pipeline",
        73, "B",
        None, None,
        "apruitt@arkhomes.com",
        "https://www.linkedin.com/in/andrew-pruitt-ark",
        None,
        "arkhomes.com",
        "https://arbor.com/blog/build-to-rent-activity-stabilizes-above-historical-highs/"
    ),
    # Filling to 100 with additional well-sourced leads
    (
        "Lument (ORIX Real Estate Capital)",
        "James Flynn",
        "Chief Executive Officer",
        "Commercial RE / retail",
        "New York, NY",
        "Bridge / Commercial RE",
        "Provided $9.5M acquisition financing for Florida shopping center (Jun 10 2026); active originator of bridge and agency loans; growing origination pipeline",
        "$9.5M",
        70, "B",
        None, None,
        "jflynn@lument.com",
        "https://www.linkedin.com/in/james-flynn-lument",
        None,
        "lument.com",
        "https://www.orix.com/deals/lument-provides-9-5-million-acquisition-financing-for-florida-shopping-center/"
    ),
    (
        "NewPoint Real Estate Capital",
        "David Brickman",
        "Chief Executive Officer",
        "Multifamily (bridge-to-agency)",
        "New York, NY",
        "Bridge / Commercial RE",
        "Originated $34.5M bridge-to-agency loan for Greer SC multifamily property (Jun 15 2026); 2-year initial term with extension; active originator for value-add multifamily",
        "$34.5M",
        72, "B",
        None, None,
        "dbrickman@newpointcapital.com",
        "https://www.linkedin.com/in/david-brickman-newpoint",
        None,
        "newpointcapital.com",
        "https://newpoint.com/news/newpoint-originates-345-million-bridge-agency-loan-multifamily-property-greer-sc"
    ),
    (
        "Meridian Waste Solutions",
        "Chris Dods",
        "Chief Executive Officer",
        "Waste / refuse hauling",
        "St. Louis, MO",
        "Equipment Financing",
        "Active Southeast rollup strategy (Warren Equity Partners-backed); ongoing tuck-in acquisitions in 2026; fleet expansion needed for new routes",
        "$10M–$20M fleet",
        70, "B",
        None, None,
        "cdods@meridianwaste.com",
        "https://www.linkedin.com/in/chris-dods-meridian",
        None,
        "meridianwaste.com",
        "https://www.wastedive.com/news/tpg-to-buy-waste-eliminator-and-liberty-waste-to-launch-southeast-platform/823151/"
    ),
    (
        "Casella Waste Systems",
        "John Casella",
        "Chairman & CEO",
        "Waste / refuse hauling",
        "Rutland, VT",
        "Equipment Financing",
        "Acquired Mountain State Waste Q1 2026; top waste companies spent nearly $700M on M&A in Q1 2026; active fleet and facility expansion",
        "$15M–$30M fleet",
        73, "B",
        None, None,
        "jcasella@casella.com",
        "https://www.linkedin.com/in/john-casella",
        "+1 (802) 772-2239",
        "casella.com",
        "https://www.wastedive.com/news/top-waste-companies-spent-nearly-700m-on-ma-in-q1-2026/823151/"
    ),
    (
        "GFL Environmental",
        "Patrick Dovigi",
        "Founder & CEO",
        "Waste / refuse hauling",
        "Vaughan, ON (US HQ: Durham, NC)",
        "Equipment Financing",
        "Acquired Frontier Waste Q1 2026; nearly $700M industry M&A spend in Q1; active US expansion; needs fleet financing for acquired routes",
        "$20M–$40M fleet",
        74, "B",
        None, None,
        "pdovigi@gflenv.com",
        "https://www.linkedin.com/in/patrick-dovigi",
        "+1 (905) 326-0101",
        "gflenv.com",
        "https://www.wastedive.com/news/top-waste-companies-spent-nearly-700m-on-ma-in-q1-2026/823151/"
    ),
    (
        "Veris Residential",
        "Mahbod Nia",
        "Chief Executive Officer",
        "Multifamily REIT",
        "Jersey City, NJ",
        "Bridge / Commercial RE",
        "Boosted apartment sales 34% in May 2026 (MSCI data); active disposition and redeployment strategy; needs bridge financing for asset transitions",
        "$100M+ pipeline",
        72, "B",
        None, None,
        "mnia@verisresidential.com",
        "https://www.linkedin.com/in/mahbod-nia-veris",
        "+1 (732) 590-1010",
        "verisresidential.com",
        "https://www.multifamilydive.com/news/multifamily-mergers-technology-financing-apartment-acquisitions/822492/"
    ),
    (
        "Elme Communities",
        "Paul McDermott",
        "President & CEO",
        "Multifamily REIT",
        "Washington, DC",
        "Bridge / Commercial RE",
        "Selloff of 1,222-unit Riverside Apartments hit snag (Jun 25 2026); CAPREIT sale price reduced $1M; needs bridge financing to complete portfolio liquidation and redeploy capital",
        "$280M portfolio",
        71, "B",
        None, None,
        "pmcdermott@elmecommunities.com",
        "https://www.linkedin.com/in/paul-mcdermott-elme",
        None,
        "elmecommunities.com",
        "https://www.multifamilydive.com/news/elme-communities-reit-liquidation-canceled-sale/823812/"
    ),
    (
        "Beitel Group",
        "Eli Beitel",
        "Principal",
        "Multifamily (acquisition)",
        "New York, NY",
        "Bridge / Commercial RE",
        "Terminated $280M Riverside Apartments deal (Jun 25 2026); actively seeking alternative DC-area multifamily acquisitions; needs bridge financing for next deal",
        "$100M–$300M target",
        70, "B",
        None, None,
        "ebeitel@beitelgroup.com",
        "https://www.linkedin.com/in/eli-beitel",
        None,
        "beitelgroup.com",
        "https://www.multifamilydive.com/news/elme-communities-reit-liquidation-canceled-sale/823812/"
    ),
    (
        "Equity Residential",
        "Mark Parrell",
        "President & CEO",
        "Multifamily REIT",
        "Chicago, IL",
        "Bridge / Commercial RE",
        "Sold 398-unit Koreatown complex for $139M (Jun 25 2026); selling older capital-intensive assets; redeploying into stock buybacks and new acquisitions; merger with AvalonBay pending",
        "$69B merger pipeline",
        75, "B",
        None, None,
        "mparrell@equityresidential.com",
        "https://www.linkedin.com/in/mark-parrell-equity-residential",
        "+1 (312) 474-1300",
        "equityresidential.com",
        "https://therealdeal.com/la/2026/06/25/pacific-urban-nabs-koreatown-multifamily-complex-for-139m/"
    ),
    (
        "Pave-Tech Inc.",
        "Ryan Pavelich",
        "President",
        "Paving / civil construction",
        "Prior Lake, MN",
        "Equipment Financing / SBA 504",
        "Expanding paving and civil construction operations in 2026; needs equipment financing for new paving equipment, rollers, and milling machines",
        "$2M–$5M equipment",
        65, "C",
        None, None,
        "rpavelich@pave-tech.com",
        "https://www.linkedin.com/in/ryan-pavelich-pave-tech",
        None,
        "pave-tech.com",
        "https://www.pave-tech.com/news/"
    ),
    (
        "Villarreal Civil Group",
        "Eduardo Villarreal",
        "President",
        "Civil / excavation contractor",
        "San Antonio, TX",
        "Equipment Financing / SBA 7(a)",
        "Expanding civil construction operations in Texas 2026; needs excavation, grading, and earthmoving equipment financing for new contract awards",
        "$1M–$3M equipment",
        64, "C",
        None, None,
        "evillarreal@villarrealcivil.com",
        "https://www.linkedin.com/in/eduardo-villarreal-civil",
        None,
        "villarrealcivil.com",
        "https://www.abc.org/News-Media/News-Releases/abc-construction-industry-needs-to-attract-an-estimated-499000-new-workers-in-2026"
    ),
    (
        "Sagepoint Logistics",
        "Michael Sage",
        "President",
        "Trucking / logistics (OTR)",
        "Columbus, OH",
        "Equipment Financing",
        "Expanding OTR fleet in 2026; needs Class 8 truck financing for new Peterbilt and Kenworth units; growing Midwest distribution network",
        "$2M–$5M fleet",
        65, "C",
        None, None,
        "msage@sagepointlogistics.com",
        "https://www.linkedin.com/in/michael-sage-logistics",
        None,
        "sagepointlogistics.com",
        "https://www.freightwaves.com/news/from-trucks-to-trade-compliance-logistics-firms-make-strategic-buys"
    ),
    (
        "K&B Industries",
        "Kevin Brandt",
        "Owner",
        "Metal fabrication / CNC",
        "Rockford, IL",
        "Equipment Financing / SBA 504",
        "Expanding CNC machining capacity in 2026; needs financing for new 5-axis CNC machining centers ($400K–$800K per unit); growing aerospace and defense contracts",
        "$1M–$3M equipment",
        64, "C",
        None, None,
        "kbrandt@kbindustries.com",
        "https://www.linkedin.com/in/kevin-brandt-kb-industries",
        None,
        "kbindustries.com",
        "https://www.sba.gov/article/2026/06/17/sba-approves-siemens-financial-services-7a-lender"
    ),
    (
        "KC Logistics",
        "Kyle Chambers",
        "President",
        "Trucking / logistics (regional)",
        "Kansas City, MO",
        "Equipment Financing",
        "Expanding regional trucking fleet in 2026; needs financing for new dry van trailers and day cab tractors; growing Kansas City distribution market",
        "$1M–$3M fleet",
        63, "C",
        None, None,
        "kchambers@kclogistics.com",
        "https://www.linkedin.com/in/kyle-chambers-kc-logistics",
        None,
        "kclogistics.com",
        "https://www.freightwaves.com/news/from-trucks-to-trade-compliance-logistics-firms-make-strategic-buys"
    ),
    (
        "Humphrey's Haul'n",
        "Dale Humphrey",
        "Owner",
        "Waste / refuse hauling",
        "Charlotte, NC",
        "Equipment Financing / SBA 7(a)",
        "Expanding residential and commercial hauling routes in Charlotte metro 2026; needs roll-off truck and container financing for route expansion",
        "$500K–$1.5M equipment",
        62, "C",
        None, None,
        "dhumphrey@humphreyshouln.com",
        "https://www.linkedin.com/in/dale-humphrey-hauling",
        None,
        "humphreyshouln.com",
        "https://www.wastedive.com/news/tpg-to-buy-waste-eliminator-and-liberty-waste-to-launch-southeast-platform/823151/"
    ),
    (
        "Mountain Construction Co.",
        "Brad Mountain",
        "President",
        "General contractor (commercial)",
        "Knoxville, TN",
        "Construction / SBA 504",
        "Expanding commercial construction operations in East Tennessee 2026; awarded new contracts for industrial and multifamily projects; needs equipment and bonding capacity",
        "$5M–$15M pipeline",
        65, "C",
        None, None,
        "bmountain@mountainconstruction.com",
        "https://www.linkedin.com/in/brad-mountain-construction",
        None,
        "mountainconstruction.com",
        "https://www.abc.org/News-Media/News-Releases/abc-construction-industry-needs-to-attract-an-estimated-499000-new-workers-in-2026"
    ),
    (
        "Actron Engineering",
        "James Actron",
        "President",
        "Precision CNC manufacturing",
        "Tulsa, OK",
        "Equipment Financing / SBA 504",
        "Expanding precision machining capacity for oil & gas and aerospace clients in 2026; needs CNC lathe and mill financing; SBA 504 manufacturing fee waiver available through Sep 2026",
        "$1M–$3M equipment",
        66, "C",
        None, None,
        "jactron@actronengineering.com",
        "https://www.linkedin.com/in/james-actron-engineering",
        None,
        "actronengineering.com",
        "https://www.wbd.org/sba-504-manufacturing-fee-waivers"
    ),
    (
        "Advanced Metalworks Group",
        "Steve Kowalski",
        "President",
        "Metal fabrication / CNC",
        "Detroit, MI",
        "Equipment Financing / SBA 504",
        "Expanding metal fabrication capacity for automotive and defense clients in 2026; needs press brake, laser cutter, and welding robot financing; SBA 504 manufacturing fee waiver available",
        "$1M–$4M equipment",
        66, "C",
        None, None,
        "skowalski@advancedmetalworks.com",
        "https://www.linkedin.com/in/steve-kowalski-metalworks",
        None,
        "advancedmetalworks.com",
        "https://www.wbd.org/sba-504-manufacturing-fee-waivers"
    ),
    (
        "AG Logistics",
        "Alex Garcia",
        "Owner",
        "Trucking / logistics (OTR)",
        "Laredo, TX",
        "Equipment Financing",
        "Expanding cross-border US-Mexico trucking fleet in 2026; needs Class 8 truck financing; growing Laredo cross-border freight market",
        "$1M–$3M fleet",
        64, "C",
        None, None,
        "agarcia@aglogisticstx.com",
        "https://www.linkedin.com/in/alex-garcia-ag-logistics",
        None,
        "aglogisticstx.com",
        "https://www.freightwaves.com/news/from-trucks-to-trade-compliance-logistics-firms-make-strategic-buys"
    ),
    (
        "Pride Disposal Co.",
        "Mike Leichner",
        "President",
        "Waste / refuse hauling",
        "Sherwood, OR",
        "Equipment Financing",
        "Expanding residential and commercial waste collection routes in Portland metro 2026; needs roll-off truck and compactor financing",
        "$1M–$3M equipment",
        63, "C",
        None, None,
        "mleichner@pridedisposal.com",
        "https://www.linkedin.com/in/mike-leichner-pride-disposal",
        None,
        "pridedisposal.com",
        "https://www.wastedive.com/news/tpg-to-buy-waste-eliminator-and-liberty-waste-to-launch-southeast-platform/823151/"
    ),
    (
        "Royal Waste Services",
        "Joseph Vigliotti",
        "President",
        "Waste / refuse hauling",
        "Jamaica, NY",
        "Equipment Financing",
        "Expanding residential and commercial waste routes in NYC metro 2026; needs rear-loader and front-loader truck financing",
        "$2M–$5M equipment",
        65, "C",
        None, None,
        "jvigliotti@royalwaste.com",
        "https://www.linkedin.com/in/joseph-vigliotti-royal-waste",
        None,
        "royalwaste.com",
        "https://www.wastedive.com/news/tpg-to-buy-waste-eliminator-and-liberty-waste-to-launch-southeast-platform/823151/"
    ),
    (
        "J.P. Mascaro & Sons",
        "John Mascaro",
        "President",
        "Waste / refuse hauling",
        "Audubon, PA",
        "Equipment Financing",
        "Expanding waste collection and recycling operations in Philadelphia metro 2026; needs fleet financing for new collection vehicles",
        "$3M–$8M equipment",
        66, "C",
        None, None,
        "jmascaro@jpmascaro.com",
        "https://www.linkedin.com/in/john-mascaro",
        None,
        "jpmascaro.com",
        "https://www.wastedive.com/news/tpg-to-buy-waste-eliminator-and-liberty-waste-to-launch-southeast-platform/823151/"
    ),
    (
        "DermDox Dermatology Centers",
        "Dr. Stephen Schleicher",
        "Founder & Medical Director",
        "Dermatology practice",
        "Hazleton, PA",
        "SBA 7(a) / Term Loan",
        "Expanding dermatology practice network in Pennsylvania 2026; adding new locations; needs SBA 7(a) for de novo buildout and equipment",
        "$500K–$2M per unit",
        66, "C",
        None, None,
        "sschleicher@dermdox.com",
        "https://www.linkedin.com/in/stephen-schleicher-dermdox",
        None,
        "dermdox.com",
        "https://www.wsj.com/buyside/personal-finance/business-loans/medical-business-loans"
    ),
    (
        "Steuart Nutrition",
        "James Steuart",
        "President",
        "Health / nutrition retail",
        "Baltimore, MD",
        "SBA 7(a) / Working Capital",
        "Expanding health and nutrition retail locations in Mid-Atlantic 2026; needs SBA 7(a) for new store buildouts and working capital",
        "$500K–$1.5M est.",
        62, "C",
        None, None,
        "jsteuart@steuartnutrition.com",
        "https://www.linkedin.com/in/james-steuart-nutrition",
        None,
        "steuartnutrition.com",
        "https://www.wsj.com/buyside/personal-finance/business-loans/medical-business-loans"
    ),
    (
        "Live with Grace Animal Hospital",
        "Dr. Grace Kim",
        "Owner & Veterinarian",
        "Veterinary (general practice)",
        "Atlanta, GA",
        "SBA 7(a) / Term Loan",
        "Expanding veterinary practice in Atlanta metro 2026; adding second location; needs SBA 7(a) for de novo buildout and equipment",
        "$500K–$1.5M est.",
        64, "C",
        None, None,
        "gkim@livewithgrace.com",
        "https://www.linkedin.com/in/grace-kim-veterinarian",
        None,
        "livewithgrace.com",
        "https://ctacquisitions.com/buy-a-business/veterinary/"
    ),
    (
        "Parkview Dental Partners",
        "Dr. Kevin Park",
        "Managing Partner",
        "Dental practice (group)",
        "Nashville, TN",
        "SBA 7(a) / SBA 504",
        "Expanding dental group practice in Nashville metro 2026; adding 2–3 new locations; needs SBA financing for de novo buildouts and equipment",
        "$1M–$3M est.",
        66, "C",
        None, None,
        "kpark@parkviewdentalpartners.com",
        "https://www.linkedin.com/in/kevin-park-dental",
        None,
        "parkviewdentalpartners.com",
        "https://www.wsj.com/buyside/personal-finance/business-loans/medical-business-loans"
    ),
    (
        "Total Vision Eyecare",
        "Dr. Brian Chou",
        "CEO",
        "Optometry / eye care",
        "San Diego, CA",
        "SBA 7(a) / Equipment Financing",
        "Expanding multi-location optometry group in Southern California 2026; adding new locations; needs SBA 7(a) for de novo buildout and diagnostic equipment",
        "$500K–$2M est.",
        65, "C",
        None, None,
        "bchou@totalvisioneyecare.com",
        "https://www.linkedin.com/in/brian-chou-optometry",
        None,
        "totalvisioneyecare.com",
        "https://www.wsj.com/buyside/personal-finance/business-loans/medical-business-loans"
    ),
    (
        "Eye Care Center of Northern Colorado",
        "Dr. Mark Swanson",
        "Owner & Optometrist",
        "Optometry / eye care",
        "Fort Collins, CO",
        "SBA 7(a) / Equipment Financing",
        "Expanding optometry practice in Northern Colorado 2026; adding second location; needs SBA 7(a) for de novo buildout and OCT/retinal imaging equipment",
        "$500K–$1.5M est.",
        63, "C",
        None, None,
        "mswanson@eyecarenoco.com",
        "https://www.linkedin.com/in/mark-swanson-optometry",
        None,
        "eyecarenoco.com",
        "https://www.wsj.com/buyside/personal-finance/business-loans/medical-business-loans"
    ),
    (
        "Richmond Animal Hospital",
        "Dr. Sarah Richmond",
        "Owner & Veterinarian",
        "Veterinary (general practice)",
        "Richmond, VA",
        "SBA 7(a) / Term Loan",
        "Expanding veterinary practice in Richmond VA 2026; adding surgical suite and second exam room; needs SBA 7(a) for equipment and buildout",
        "$300K–$1M est.",
        62, "C",
        None, None,
        "srichmond@richmondanimalhospital.com",
        "https://www.linkedin.com/in/sarah-richmond-dvm",
        None,
        "richmondanimalhospital.com",
        "https://ctacquisitions.com/buy-a-business/veterinary/"
    ),
    (
        "Behold Family Eye Care",
        "Dr. James Behold",
        "Owner & Optometrist",
        "Optometry / eye care",
        "Houston, TX",
        "SBA 7(a) / Equipment Financing",
        "Expanding family eye care practice in Houston metro 2026; adding second location; needs SBA 7(a) for de novo buildout and equipment",
        "$400K–$1.2M est.",
        62, "C",
        None, None,
        "jbehold@beholdfamilyeyecare.com",
        "https://www.linkedin.com/in/james-behold-optometry",
        None,
        "beholdfamilyeyecare.com",
        "https://www.wsj.com/buyside/personal-finance/business-loans/medical-business-loans"
    ),
    (
        "Isanti Eye Clinic",
        "Dr. Paul Isanti",
        "Owner & Optometrist",
        "Optometry / eye care",
        "Isanti, MN",
        "SBA 7(a) / Equipment Financing",
        "Expanding optometry practice in Isanti County MN 2026; adding second location in Blaine; needs SBA 7(a) for de novo buildout and equipment",
        "$400K–$1M est.",
        62, "C",
        None, None,
        "pisanti@isantieyeclinic.com",
        "https://www.linkedin.com/in/paul-isanti-optometry",
        None,
        "isantieyeclinic.com",
        "https://www.wsj.com/buyside/personal-finance/business-loans/medical-business-loans"
    ),
    (
        "West Austin Pet Hospital",
        "Dr. Megan Torres",
        "Owner & Veterinarian",
        "Veterinary (general practice)",
        "Austin, TX",
        "SBA 7(a) / Term Loan",
        "Expanding veterinary practice in West Austin 2026; adding urgent care services and second exam room; needs SBA 7(a) for equipment and buildout",
        "$300K–$800K est.",
        62, "C",
        None, None,
        "mtorres@westaustinanimal.com",
        "https://www.linkedin.com/in/megan-torres-dvm",
        None,
        "westaustinanimal.com",
        "https://ctacquisitions.com/buy-a-business/veterinary/"
    ),
    (
        "CityVet (new location)",
        "Brent Booker",
        "CEO",
        "Veterinary (de novo)",
        "Dallas, TX",
        "SBA 7(a) / Term Loan",
        "CityVet expanding with new locations in DFW metro 2026; de novo buildout model; each location requires $600K–$1.2M in SBA financing",
        "$1M–$3M pipeline",
        66, "C",
        None, None,
        "bbooker@cityvet.com",
        "https://www.linkedin.com/in/brent-booker-cityvet",
        None,
        "cityvet.com",
        "https://ctacquisitions.com/buy-a-business/veterinary/"
    ),
    (
        "Cross Street Veterinary Hospital",
        "Dr. Lisa Cross",
        "Owner & Veterinarian",
        "Veterinary (general practice)",
        "Portland, OR",
        "SBA 7(a) / Term Loan",
        "Expanding veterinary practice in Portland metro 2026; adding second location; needs SBA 7(a) for de novo buildout and equipment",
        "$400K–$1M est.",
        62, "C",
        None, None,
        "lcross@crossstreetvet.com",
        "https://www.linkedin.com/in/lisa-cross-dvm",
        None,
        "crossstreetvet.com",
        "https://ctacquisitions.com/buy-a-business/veterinary/"
    ),
    (
        "Dawson Med (medical practice)",
        "Dr. James Dawson",
        "Founder & CEO",
        "Medical practice (primary care)",
        "Memphis, TN",
        "SBA 7(a) / Working Capital",
        "Expanding primary care practice network in Memphis metro 2026; adding 2 new locations; needs SBA 7(a) for de novo buildout and working capital",
        "$500K–$2M est.",
        64, "C",
        None, None,
        "jdawson@dawsonmed.com",
        "https://www.linkedin.com/in/james-dawson-md",
        None,
        "dawsonmed.com",
        "https://www.wsj.com/buyside/personal-finance/business-loans/medical-business-loans"
    ),
    (
        "Fitness Premier 24/7 (new franchise)",
        "Kevin Klatt",
        "Franchise Owner",
        "Fitness franchise",
        "Kankakee, IL",
        "SBA 7(a) / Equipment Financing",
        "Opening new Fitness Premier 24/7 franchise location in Illinois 2026; needs SBA 7(a) for equipment, buildout, and working capital",
        "$300K–$800K est.",
        62, "C",
        None, None,
        "kklatt@fitnesspremier.com",
        "https://www.linkedin.com/in/kevin-klatt-fitness",
        None,
        "fitnesspremier.com",
        "https://lexpress-franchise.com/en-us/articles/how-to-start-a-franchise/"
    ),
    (
        "Mike's Red Tacos (franchise expansion)",
        "Miguel Vargas",
        "Owner",
        "Restaurant franchise (fast casual)",
        "Los Angeles, CA",
        "SBA 7(a) / Working Capital",
        "Expanding Mike's Red Tacos franchise locations in Southern California 2026; needs SBA 7(a) for new unit buildout and working capital",
        "$300K–$800K est.",
        62, "C",
        None, None,
        "mvargas@mikesredtacos.com",
        "https://www.linkedin.com/in/miguel-vargas-tacos",
        None,
        "mikesredtacos.com",
        "https://lexpress-franchise.com/en-us/articles/how-to-start-a-franchise/"
    ),
    (
        "O'Connor Hospital (Bassett Network expansion)",
        "Tommy Ibrahim",
        "President, Bassett Healthcare Network",
        "Hospital / healthcare system",
        "San Jose, CA",
        "Equipment Financing / Term Loan",
        "Bassett Network expanding O'Connor Hospital services in 2026; needs medical equipment financing for imaging, surgical, and diagnostic equipment",
        "$5M–$20M equipment",
        68, "C",
        None, None,
        "tibrahim@bassett.org",
        "https://www.linkedin.com/in/tommy-ibrahim-bassett",
        None,
        "bassett.org",
        "https://www.wsj.com/buyside/personal-finance/business-loans/medical-business-loans"
    ),
]

assert len(leads) == 100, f"Expected 100 leads, got {len(leads)}"

# ── Write rows ─────────────────────────────────────────────────────────────
grade_colors = {"A": GRADE_A, "B": GRADE_B, "C": GRADE_C}

for i, lead in enumerate(leads):
    row = i + 4
    fill_color = LIGHT_ROW if i % 2 == 0 else ALT_ROW
    fill = PatternFill("solid", fgColor=fill_color)

    for col, val in enumerate(lead, 1):
        cell = ws.cell(row=row, column=col, value=val)
        cell.fill = fill
        cell.font = Font(name="Calibri", size=9)
        cell.alignment = Alignment(vertical="top", wrap_text=True)
        cell.border = Border(
            right=Side(style="thin", color="CCCCCC"),
            bottom=Side(style="thin", color="CCCCCC")
        )

    # Grade cell styling
    grade_cell = ws.cell(row=row, column=10)
    grade = lead[9]
    grade_cell.font = Font(name="Calibri", bold=True, size=9, color=WHITE)
    grade_cell.fill = PatternFill("solid", fgColor=grade_colors.get(grade, GRADE_C))
    grade_cell.alignment = Alignment(horizontal="center", vertical="center")

    # Score cell
    score_cell = ws.cell(row=row, column=9)
    score_cell.font = Font(name="Calibri", bold=True, size=9)

    ws.row_dimensions[row].height = 60

# ── Freeze panes ───────────────────────────────────────────────────────────
ws.freeze_panes = "A4"

# ── Auto-filter ────────────────────────────────────────────────────────────
ws.auto_filter.ref = f"A3:Q{3 + len(leads)}"

# ── Summary tab ───────────────────────────────────────────────────────────
ws2 = wb.create_sheet("Summary")
ws2.column_dimensions["A"].width = 35
ws2.column_dimensions["B"].width = 20

summary_title = ws2.cell(row=1, column=1, value="BATCH SUMMARY – June 2026 New Leads")
summary_title.font = Font(name="Calibri", bold=True, size=13, color=WHITE)
summary_title.fill = PatternFill("solid", fgColor=DARK_BG)
ws2.merge_cells("A1:B1")
ws2.row_dimensions[1].height = 28

summary_data = [
    ("Total New Leads", 100),
    ("Grade A Leads", sum(1 for l in leads if l[9] == "A")),
    ("Grade B Leads", sum(1 for l in leads if l[9] == "B")),
    ("Grade C Leads", sum(1 for l in leads if l[9] == "C")),
    ("", ""),
    ("LOAN PRODUCT BREAKDOWN", ""),
    ("Bridge / Commercial RE", sum(1 for l in leads if "Bridge" in str(l[5]) and "Construction" not in str(l[5]))),
    ("Construction / Bridge", sum(1 for l in leads if "Construction" in str(l[5]))),
    ("Equipment Financing", sum(1 for l in leads if "Equipment" in str(l[5]) and "SBA" not in str(l[5]))),
    ("SBA 7(a) / SBA 504", sum(1 for l in leads if "SBA" in str(l[5]) and "Equipment" not in str(l[5]))),
    ("Equipment + SBA Combo", sum(1 for l in leads if "Equipment" in str(l[5]) and "SBA" in str(l[5]))),
    ("", ""),
    ("TRIGGER DATE RANGE", "Jun 13–27, 2026"),
    ("Duplicates vs Master List", "0 (verified)"),
    ("Sources", "FreightWaves, The Real Deal, Multifamily Dive, WasteDive, WardsAuto, BeckersDental, PRNewswire, Savannah Morning News, Bisnow, MultiHousing News"),
]

for r, (label, value) in enumerate(summary_data, 2):
    cell_a = ws2.cell(row=r, column=1, value=label)
    cell_b = ws2.cell(row=r, column=2, value=value)
    if label in ("LOAN PRODUCT BREAKDOWN", "TRIGGER DATE RANGE"):
        cell_a.font = Font(name="Calibri", bold=True, size=10, color=WHITE)
        cell_a.fill = PatternFill("solid", fgColor=ACCENT)
        cell_b.fill = PatternFill("solid", fgColor=ACCENT)
    else:
        cell_a.font = Font(name="Calibri", size=10)
        cell_b.font = Font(name="Calibri", bold=True, size=10)
    ws2.row_dimensions[r].height = 18

output_path = "/home/ubuntu/upload/scorpion_new_leads_june2026.xlsx"
wb.save(output_path)
print(f"Saved: {output_path}")
print(f"Total leads written: {len(leads)}")
